### ISSUE TITLE
Add native support for OF VR 

### ISSUE THREAD

**Issue by jshube2** [grailbio/go-dicom#11]
Awesome and very helpful library so far.

However, It would be cool if there was native support for the "OF" VR so that we could natively return a []float32 instead of the []string that it defaults to.

**Comment by yasushi-saito** [comment]
Do you have a dicom file that contains OF or OD? I can't find any example in the wild.

**Comment by jshube2** [comment]
Attched is an anonymized example which contains an OF field.

The (0066, 0016) Point Coordinates Data tag uses OF

**Comment by jshube2** [comment]
Alternative source: http://s000.tinyupload.com/?file_id=62058346885506470497
