### ISSUE TITLE
get dataSet value by dicomTag

### ISSUE THREAD

**Issue by ASVBPREAUBV** [grailbio/go-dicom#12]
is there a way to get a value of a dataset element by dicomtag?
e.g.:
`ds.Elements.getByDicomTag(dicomtag.StudyInstanceUID)`
instead:
`
for _, ele := range ds.Elements {
		if ele.Tag == dicomtag.StudyInstanceUID {
			return ele.Value
		}
}
`

**Comment by yasushi-saito** [comment]
ds.FindElementByTag(dicomtag.StudyInstanceUID)

or dicom.FindElementByTag(ds.Elements, dicomtag.StudyInstanceUID)

**Comment by ASVBPREAUBV** [comment]
Ah ok sorry. Thanks for the reply.
