### ISSUE TITLE
Get custom Dicom Header

### ISSUE THREAD

**Issue by paul-asvb** [grailbio/go-dicom#13]
Is there a way to get custom Dicom headers?

**Comment by yasushi-saito** [comment]
What do you mean by custom headers? There's no concept of "header" per se. DICOM file is just a collection of elements, some of them text and some of them images.

**Comment by ASVBPREAUBV** [comment]
Thanks for the reply. Im working with DICOMs from different manufacturers. They add additional headers to the files. i tried getting them by makeing custom Tags: 
eg.: Philipps "NumberOfSlicesMR"
`dicomtag.Tag{0x2001, 0x1018}`
the output of FindElementByTag is invalid though.

**Comment by yasushi-saito** [comment]
Passing a private tag to FindElementTag and others should just work; we don't special-case such tags. If you can provide us an anonymized version of the file, I can take a look.

**Comment by ASVBPREAUBV** [comment]
Thanks for the answer. Ill try to get the file anonymized

**Comment by siddharthab** [comment]
Sorry, but we are no longer working on this project and are archiving this repository.
