### ISSUE TITLE
Panicking on ReadElement failed to consume data

### ISSUE THREAD

**Issue by carbocation** [grailbio/go-dicom#15]
Google Storage frequently throws input/output errors. My code anticipates this and handles it. However, when I call into god-dicom, the code panics because go-dicom panics in ReadDataSet. It seems like it could instead return an error, no?

https://github.com/grailbio/go-dicom/blob/c30d9eaca591167c994ee755779e902bf6752b5e/dicom.go#L108

**Comment by siddharthab** [comment]
Sorry, but we are no longer working on this project and are archiving this repository.
