### ISSUE TITLE
v.io/x/lib/vlog causing errors

### ISSUE THREAD

**Issue by dbkaplun** [grailbio/go-dicom#4]
Hi @grailbio, the `v.io/x/lib/vlog` import is causing errors when vendoring. I believe the new source for https://v.io/x/lib is https://github.com/vanadium/go.lib. Please update the repo to reflect the new path. Thanks!

**Comment by yasushi-saito** [comment]
This is a temporary issue. v.io should be up again soon. Sorry for the problem.

**Comment by yasushi-saito** [comment]
It's working now.

**Comment by addijhaq** [comment]
still causing errors... redirects to broken link.

**Comment by razvanm** [comment]
How exactly are you hitting an error?

Things looks fine to me.

```
$ curl 'https://v.io/x/lib/vlog?go-get=1'
<html><head><meta name="go-import" content="v.io/x/lib git https://github.com/vanadium/go.lib"/></head></html>
$
```
Also, a `go get v.io/x/lib/vlog` in an empty workspace also works fine.
