### ISSUE TITLE
Unexpected extra flags

### ISSUE THREAD

**Issue by vdemario** [grailbio/go-dicom#5]
Hi. First of all, thanks for building this project, I've just started using it and it has already been very helpful.

I built a simple program to extract some basic information from a DICOM file such as the patient name and added a few flags to my program via the `flag` package in the stdlib.

When I ran my binary with `--help` I was surprised to see a lot of extra flags, such as `-v`, `-vmodule` and others. Looks like this is from the vlog library. I'm not sure what that library does and I wouldn't expect to get a bunch of new flags registered just by importing a new lib. Is it really necessary? Are there any known ways around it?

If the only way around it is to remove the dependency, would you like if I submitted a PR doing that? I don't know anything about vlog but I'm assuming it's a logging library, if that's the case it shouldn't be difficult.

**Comment by yasushi-saito** [comment]
These flags are added by the vlog module. This problem has happened before. Short term, I'll change to use log instead of vlog. 

Longer term, perhaps we should switch to a better-behaving logging library.

**Comment by vdemario** [comment]
Please correct me if I'm wrong, but I see go-dicom as a library only (it doesn't produce any cli tools, right?).

Since it is a library, I'm of the opinion that it shouldn't do any logging of its own, only return meaningful errors for the programs that import it to decide what to do.

Do you agree with that? If so, we could consider a second longer term objective to remove logging altogether.

**Comment by yasushi-saito** [comment]
I pushed commit 4981ba8ee23a7356609f160358d6676183ce6cfa that removes uses of vlog. It should fix the problem.

**Comment by vdemario** [comment]
@yasushi-saito what about no logging? Is that something you'd like to try?

**Comment by yasushi-saito** [comment]
go-dicom doesn't log much by default already. The one exception that's left is when the file uses an unsupported coding system. We could make this an error (I haven't seen this situation), but I left it in for now. So in general you shouldn't see any log message from the library.

Or are you talking about removing the use of the log package from the source code? I want to keep it in for debugging purpose.

**Comment by vdemario** [comment]
I was talking about removing it from the source code. An example that just happened:

`E0316 15:02:07.169181   75946 element.go:521] Warning: defined-length pixel data not supported: tag (7fe0,0010), VR=OW, VL=4568400`

That log message doesn't really let me do anything. If I had gotten an `ErrDefinedLenPixelData` or something like that I could write code to try to do something with this error.

**Comment by yasushi-saito** [comment]
Sorry, I missed it. We can downgrade it to level 1

if dicomlog.Level >= 1 { ... }

I'm hesitant to make it an error, since this is just the case of the
codebase not fully implementing the DICOM spec yet.

**Comment by vdemario** [comment]
If the error is clearly documented I would it consider it perfectly fine.
